language: java
jdk: oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: IjN6xREO2Q8y8UBN482VLiOQBPbzamnfnZv9MNFPIuTPVedkm2An3AmLFua4H8WpS1Ei2EKaW919Hfbpa00agdK5XGoonGBVobWDVK2h3aLLVRlWq/cIApJBHMlCKcQbw4YZ6Ust8wWQL3eYjxdPu/3KFfEi/qWbR7wZ8w5CayndKDyUCLzMIZgJmwkAd0ZvPkrO3L7zB0bttwfQNdGpbpPKuGAoYlYftcmSNCLzeLLcvbEYSQ/u6FKdM2174DQ2upNMNGLuACCJohl2m+nD80wSXrOMclXKXWamniNBqo9FW7BHyMcA8FeRkxHFiwFxv2ZZ89tEAxvS26lSlfrC1//Rj83YxadZCZM+o6jVFCUIej0I7dRc9fGImQEa+4PEJF/xLJw3aewux9kpEMxIKIrMPWdfM8rDOKd2iypI0/YH6wBPnHqDoTcsZMqN9c0jTSJv2uUGNo3KaQAxXaNTll5hZcAyKZTzdToGVipeiRfa3GaPsF5CMCArmbrHPM9zwCA+N8ZKV/GmxywJ+mBUiCeWA+4POOY3jS7wzEvgYAC7hAufPMQTnttCtAMuI/z+Uh7DbhNq15N5dTtl7Cbv7EPsiLGu2yrpzFZmZyTx3SyvowzQF3Uu7BOh3630PhAqWF1eCgoTk01U96wHwkSWvX0KHEqyQPZkjf5NR8DA5QU=
  app: isapi-medidas
