language: java
jdk: oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: c8bWyArFN18jRtM1Cb1q0hdc1WlUI5GTnaUPqIAASCzdAlURSbgSG2CvYTqYsw2Lt2lR3CKERLGq96HM3KHEDv32hMPqZRTg5qLUcwMDNIRVZKpX2vNoxWO8WgzBs6M99zDQRlfIH8CV+tNCP7Dv+CWfq5fKDTCYhqk7bMzqYhYK6o6c+V5ix/3g9f8pshFSEYIeIonVfj8TjjW/fEBp4oXJ6D0Zt4A3VYhXdS+4vo8wBaGfy3kka8CvmJK9ohCg6qxDtNcG3C4mKBRexgncGaDSvXHo0ZXxxqCp+5qN9rWZ5wFbvSenlKtCYJ7g7gLMo3Z5xpzXpYJxLQtCntBHdLeIHCVj0vP0n0A7EJFadLlEuHKbfdMk3d+J9JJ905tB9lS40x6fN1gkZVcgHYsKBrDDhMo9qLmGQZIqCAZMw6eZ7Q1enSbujNUcnFKaSAK8yT5OVp6EkRtybC6zw+TEaY2+yeoKS/6CIu7WbeCIuY3zWS18cotwuudkf1oCfOuISYQOn3RN8J3flSyrYdoEt4DfdoCHg4sv1hb6VWdKx18SicEv6PAb0cnnlJFTwCUleuUVXmlTCPzE/5m7bG/wdJ/2oXS3zByxNN7X7PphkBdVe3dcp/O+Kz41MMjd4uy2vn26UmLGjppOwCPph1ooNiB8lLRrAjN3K/ikM5vMqvE=
  app: isapi-medidas
